Agence/Agence/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('AgenceConnect.urls')),
    path('appchefagence/',include('AppChefAgence.urls')),
    path('pdf_convert/',include('pdf_convert.urls')),
    path('Authentification/',include('Authentification.urls')),
    

] 

Agence/AppChefAgence/urls.py
from django.urls import path
from .views import AjoutListRetrait, OperateRetrait, SupprimerTousRetraités, Supprimer_Retraite, SupprimerTouteOperation, Supprimer_Retraite_Visualisation, VoirOperation, VoirListRetrait, Supprimer_Operation_Visualisation, ChefAgence,AfficherChampsAuto, Modification_Operation,Supprimer_Operation


urlpatterns = [
    path('',ChefAgence, name="chefagence"),
    path('ajout/', AjoutListRetrait, name="ajoutlistretraite"),
    path('voir_listretraite/', VoirListRetrait, name="voir_listretraite"),
    path('operate/', OperateRetrait, name="operateretraite"),
    path('voir_operation/', VoirOperation, name="voir_operation"),
    path('afficherchampsauto/',AfficherChampsAuto, name='afficherchampsauto'),
    path('modification_operation/<int:id>/', Modification_Operation, name='modification_operation'),
    path('supprimer_operation/<int:operation_id>/', Supprimer_Operation, name='suppression_operation'),
    path('supprimer_retraite/<int:operation_id>/', Supprimer_Retraite, name='supprimer_retraite'),
    path('supprimer_operation_visualisation/<int:operation_id>/', Supprimer_Operation_Visualisation, name='supprimer_operation_visualisation'),
    path('supprimer_retraite_visualisation/<int:operation_id>/', Supprimer_Retraite_Visualisation, name='supprimer_retraite_visualisation'),
    path('supprimer_toute_operation/', SupprimerTouteOperation, name='supprimer_toute_operation'),
    path('supprimer_tous_retraités/', SupprimerTousRetraités, name='supprimer_tous_retraités'),
  
 
    
  





    
    
    



     
  

]

Agence/AppChefAgence/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.core.exceptions import ObjectDoesNotExist
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.db.models.signals import pre_delete




class ListRetraite(models.Model):
    ordre = models.IntegerField(default=0) 
    titre = models.CharField(max_length=8, validators=[RegexValidator(r'^[a-zA-Z0-9]{8}$', 'Le titre doit contenir 8 caractères alphanumériques.')])
    beneficiaire = models.CharField(max_length=255, default='')
    nni = models.CharField(max_length=10, validators=[RegexValidator(r'^[0-9]{10}$', 'Le NNI doit contenir exactement 10 chiffres.')], default='')
    date_retraite = models.DateField()
    ville = models.CharField(max_length=100)
    age = models.IntegerField()
    telephone = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titre
    
    class Meta:
        ordering = ['created_at']


# Signal pour mettre à jour le champ ordre lors de l'enregistrement
@receiver(pre_save, sender=ListRetraite)
def set_ordre(sender, instance, **kwargs):
    if instance.pk is None:
        # Nouvel enregistrement
        max_ordre = ListRetraite.objects.all().aggregate(models.Max('ordre'))['ordre__max']
        if max_ordre is None:
            max_ordre = 0
        instance.ordre = max_ordre + 1
    else:
        # Mise à jour d'un enregistrement existant
        existing_instance = ListRetraite.objects.get(pk=instance.pk)
        if existing_instance.ordre != instance.ordre:
            instance.ordre = existing_instance.ordre

# Signal pour mettre à jour les ordres lors de la suppression
@receiver(pre_delete, sender=ListRetraite)
def update_order_on_delete_retraire(sender, instance, **kwargs):
    # Récupérer tous les objets dont l'ordre est supérieur à celui supprimé
    retraites_to_update = ListRetraite.objects.filter(ordre__gt=instance.ordre)
    for retraite in retraites_to_update:
        # Décrémenter l'ordre de chaque objet
        retraite.ordre -= 1
        retraite.save()  



        
class OperateRetraite(models.Model):
    ordre = models.IntegerField()
    Numero_titre = models.ForeignKey(ListRetraite, on_delete=models.CASCADE, blank=True, null=True)
    montant = models.DecimalField(max_digits=10, decimal_places=2)
    beneficiaire = models.CharField(max_length=255, default='')
    nni = models.CharField(max_length=10, validators=[RegexValidator(r'^[0-9]{10}$', 'Le NNI doit contenir exactement 10 chiffres.')], default='')
    date_operation = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.Numero_titre.titre} - Montant: {self.montant}"
    
    class Meta:
        ordering = ['date_operation']
    
@receiver(pre_save, sender=OperateRetraite)
def update_order_on_create(sender, instance, **kwargs):
    if not instance.pk:  # Nouvelle instance
        try:
            last_instance = sender.objects.latest('ordre')
            instance.ordre = last_instance.ordre + 1
        except ObjectDoesNotExist:
            instance.ordre = 1
        



@receiver(pre_delete, sender=(OperateRetraite))
def update_order_on_delete(sender, instance, **kwargs):
    # Obtenez toutes les instances avec un ordre supérieur à celui supprimé
    instances_to_update = sender.objects.filter(ordre__gt=instance.ordre)
    # Décrémentez l'ordre de chaque instance suivante
    for instance_to_update in instances_to_update:
        instance_to_update.ordre -= 1
        instance_to_update.save()
        

Agence/AppChefAgence/forms.py
from django import forms
from .models import ListRetraite, OperateRetraite

class ListRetraiteForm(forms.ModelForm):
    class Meta:
        model = ListRetraite
        fields = ['titre', 'beneficiaire', 'nni', 'date_retraite', 'ville', 'age', 'telephone']
        widgets = {
            'titre': forms.TextInput(attrs={'class': 'form-control', 'onchange': 'updateOperateRetraiteFields()'}),
            'beneficiaire': forms.TextInput(attrs={'class': 'form-control'}),
            'nni': forms.TextInput(attrs={'class': 'form-control'}),
            'date_retraite': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'ville': forms.TextInput(attrs={'class': 'form-control'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'telephone': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
        
        

class OperateRetraiteForm(forms.ModelForm):
    class Meta:
        model = OperateRetraite
        fields = ['Numero_titre', 'beneficiaire', 'nni', 'montant']
        widgets = {
            'beneficiaire': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
            'nni': forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(OperateRetraiteForm, self).__init__(*args, **kwargs)
        self.fields['montant'].widget.attrs['class'] = 'form-control'

Agence/AppChefAgence/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import ListRetraite, OperateRetraite
from .forms import ListRetraiteForm, OperateRetraiteForm
from django.http import JsonResponse
from django.http import HttpResponseBadRequest 
from django.core.paginator import Paginator
from django.db.models import Sum
from django.db.models import Count






#fonction pour la page d'accueil

def ChefAgence(request):
   
    listretraite_par_ville = ListRetraite.objects.values('ville').annotate(nombre_retraites=Count('id'))

    total_retraites = ListRetraite.objects.aggregate(total_retraites=Count('id'))
    
    total_operation = OperateRetraite.objects.aggregate(total_operation=Count('id'))
    

    operate_retraites = OperateRetraite.objects.all()
    
    
    montant_inf_100000 = operate_retraites.filter(montant__lt=100000).count()
    
    montant_100000_300000 = operate_retraites.filter(montant__range=[100000, 300000]).count()
    
    montant_300000_600000 = operate_retraites.filter(montant__range=[300000, 600000]).count()
    
    montant_sup_600000 = operate_retraites.filter(montant__gte=600000).count()


    context = {
        
        'listretraite_par_ville': listretraite_par_ville,
        
        'total_retraites': total_retraites['total_retraites'], 
        
        'operate_retraites': operate_retraites,



        'montant_inf_100000': montant_inf_100000,
        
        'montant_100000_300000': montant_100000_300000,
        
        'montant_300000_600000': montant_300000_600000,
        
        'montant_sup_600000': montant_sup_600000,
        
        'total_operation': total_operation['total_operation'], 
    }

    return render(request, 'Home_branch_manage.html', context)



#fonction pour ajouter un retraité


def AjoutListRetrait(request):

    
    if request.method == 'POST':
        
        form = ListRetraiteForm(request.POST)
        
        if form.is_valid():
            
            form.save()
        else:
            
            form = ListRetraiteForm()
          
    else:
        
        form = ListRetraiteForm()
        
    
    Listeretraire = ListRetraite.objects.order_by('-created_at')[:3]
    
    context = {'form': form, 'operate': Listeretraire}
    
    return render(request, 'Add_retired.html', context)



#fonction pour ajourter une operation

def OperateRetrait(request):
    
    if request.method == 'POST':
        
        form = OperateRetraiteForm(request.POST)
        
        if form.is_valid():
            
            form.save()
    else:
        
        form = OperateRetraiteForm()
    

    operations = OperateRetraite.objects.order_by('-date_operation')[:3]

    beneficiaire = ''
    
    nni = ''
    
    if 'Numero_titre' in request.GET:
        
        numero_titre_id = request.GET.get('Numero_titre')
        
        if numero_titre_id:
            
            numero_titre = ListRetraite.objects.get(id=numero_titre_id)
            
            beneficiaire = numero_titre.beneficiaire
            
            nni = numero_titre.nni
            
            form.initial['beneficiaire'] = beneficiaire
            
            form.initial['nni'] = nni
    
    context = {'form': form, 'operate': operations, 'beneficiaire': beneficiaire, 'nni': nni}
    
    return render(request, 'Add_operation.html', context)



#fonction pour voir la liste des retraités

def VoirListRetrait(request):
    
    listretraite = ListRetraite.objects.all()
    
    paginator = Paginator(listretraite, 10)  
    
    page_number = request.GET.get('page')
    
    operate = paginator.get_page(page_number)
    
    return render(request, 'View_list_retired.html', {'operate': operate})



#fonction pour voir la liste des operations


def VoirOperation(request):

    operations = OperateRetraite.objects.all()


    paginator = Paginator(operations, 50)  
    
    page_number = request.GET.get('page')
    
    page_obj = paginator.get_page(page_number)

 
    total_montant = operations.aggregate(total_montant=Sum('montant'))['total_montant']

    if total_montant is None:
        
        total_montant = 0

    return render(request, 'View_list_operation.html', { 'page_obj': page_obj,  'total_montant': total_montant})




#fonction pour reucperer des champs beneficiaire et nni  et les affichés automatiquement

def AfficherChampsAuto(request):
    
    numero_titre_id = request.GET.get('Numero_titre')
    
    if numero_titre_id:
        
        numero_titre = ListRetraite.objects.get(id=numero_titre_id)
        
        beneficiaire = numero_titre.beneficiaire
        
        nni = numero_titre.nni
        
        return JsonResponse({'beneficiaire': beneficiaire, 'nni': nni})
    
    else:
        
        return JsonResponse({'error': 'No data found'})
    


#fonction pour la modification d'une operation

def Modification_Operation(request, id):
    
    if request.method == 'POST':
        
        identifiant = OperateRetraite.objects.get(pk=id)
        
        form = OperateRetraiteForm(request.POST, instance=identifiant)
        
        if form.is_valid():
            
            form.save()
            
        return redirect('operateretraite')
    else:
        identifiant = OperateRetraite.objects.get(pk=id)
        
        form = OperateRetraiteForm(instance=identifiant)
           

    operations = OperateRetraite.objects.all()[:10]

    beneficiaire = ''
    
    nni = ''
    
    if 'Numero_titre' in request.GET:
        
        numero_titre_id = request.GET.get('Numero_titre')
        
        if numero_titre_id:
            
            numero_titre = ListRetraite.objects.get(id=numero_titre_id)
            
            beneficiaire = numero_titre.beneficiaire
            
            nni = numero_titre.nni
            

            form.initial['beneficiaire'] = beneficiaire
            
            form.initial['nni'] = nni
    
    context = {'form': form, 'operate': operations, 'beneficiaire': beneficiaire, 'nni': nni}
    
    return render(request, 'Update_operation.html', context)



#fonction pour la suppression d'une operation

def Supprimer_Operation(request, operation_id):
    
    operation = get_object_or_404(OperateRetraite, pk=operation_id)
    
    if request.method == 'POST':
        
        operation.delete()
        
        return redirect('operateretraite')  
    
    return HttpResponseBadRequest("Méthode non autorisée")




#fonction pour supprimer toutes les operations

def SupprimerTouteOperation(request):

    OperateRetraite.objects.all().delete()
    
    return redirect('voir_operation') 



#fonction pour supprimer une operation lorsqu'on est sur la page de visualisation

def Supprimer_Operation_Visualisation(request, operation_id):
    
    operation = get_object_or_404(OperateRetraite, pk=operation_id)
    
    if request.method == 'POST':
        
        operation.delete()
        
        return redirect('voir_operation')  
    
    return HttpResponseBadRequest("Méthode non autorisée")




#fonction pour la modification d'un retraité

def Modification_Retraite(request, id):
    
    if request.method == 'POST':
        
        identifiant = ListRetraite.objects.get(pk=id)
        
        form = ListRetraiteForm(request.POST, instance=identifiant)
        
        if form.is_valid():
            
            form.save()
        return redirect('voir_listretraite')
    else:
        identifiant = ListRetraite.objects.get(pk=id)
        
        form = ListRetraiteForm(instance=identifiant)
        
        

    listeretraite = ListRetraite.objects.all()

    context = {'form': form, 'operate': listeretraite}
    
    return render(request, 'Update_operation.html', context)



#fonction pour supprimer un retraité

def Supprimer_Retraite(request, operation_id):
    
    listeretraite = get_object_or_404(ListRetraite, pk=operation_id)
    
    if request.method == 'POST':
        
        listeretraite.delete()
        
        return redirect('ajoutlistretraite')  
    
    return HttpResponseBadRequest("Méthode non autorisée")


#fonction pour supprimer tous les retraités 

def SupprimerTousRetraités(request):

    ListRetraite.objects.all().delete()
    
    return redirect('voir_listretraite') 


#fonction pour supprimer les retraité lorsqu'on est sur la page de visualisation

def Supprimer_Retraite_Visualisation(request, operation_id):
    
    operation = get_object_or_404(ListRetraite, pk=operation_id)
    
    if request.method == 'POST':
        
        operation.delete()
        
        return redirect('voir_listretraite')  
    
    return HttpResponseBadRequest("Méthode non autorisée")

Agence/AppChefAgence/templates/Add_operation.html
{% extends 'Base_branch_manage.html' %}

{% block content_Branch_manage %}
    
<!-- partial -->
<div class="main-panel">        
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-4 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Ajouter une opération</h4>
                        <p class="card-description">
                            Commencé par entrée le Numero Titre 
                        </p>
                        <div class="forms-sample mb-4">
                            <div class="form-group row mb-4">
                                <form action="" class="p-5 bg-white" method="POST">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <input type="submit" class="btn btn-primary btn-md text-whites mt-4" value="Ajouter">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Aperçu des Opérations</h4>
                        <p class="card-description">
                            Visualisation des trois dernières operations
                        </p>
                        {% if operate %}
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">N° ORDRE</th>
                                        <th scope="col">N° TITRE</th>
                                        <th scope="col">BÉNÉFICIAIRE</th>
                                        <th scope="col">NNI</th>
                                        <th scope="col">MONTANT</th>
                                        <th scope="col">DATE D'OPÉRATION</th>
                                    </tr>
                                </thead>
                                <tbody id="myTable">
                                    {% for item in operate %}
                                    <tr>
                                        <td>{{ item.ordre }}</td>
                                        <td>{{ item.Numero_titre }}</td>
                                        <td>{{ item.beneficiaire }}</td>
                                        <td>{{ item.nni }}</td>
                                        <td>{{ item.montant }}</td>
                                        <td>{{ item.date_operation }}</td>
                                        <td>
                                            <a href="{% url 'modification_operation' item.id %}" class="btn btn-primary btn-md text-whites">
                                              <i class="bi bi-pencil"></i> <!-- Icône Bootstrap pour Modifier -->
                                            </a>
                                            <button type="button" class="btn btn-danger btn-md text-whites" data-toggle="modal" data-target="#deleteModal{{ item.id }}">
                                              <i class="bi bi-trash"></i> <!-- Icône Bootstrap pour Supprimer -->
                                            </button>
                                          </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <button id="voir-operation-btn" class="btn btn-primary btn-md text-whites mt-4">Visualiser</button>
                        {% else %}
                        <h2 class="col-12 text-center">Pas d'enregistrement</h2>
                        {% endif %}
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- content-wrapper ends -->
    <!-- partial:../../partials/_footer.html -->
    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Premium <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap admin template</a> from BootstrapDash.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
        </div>
    </footer>
    <!-- partial -->
</div>
<!-- main-panel ends -->
</div>

<!-- Modal de confirmation de suppression -->
{% for item in operate %}
<div class="modal fade" id="deleteModal{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel{{ item.id }}" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel{{ item.id }}">Confirmation de suppression</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Êtes-vous sûr de vouloir supprimer cette opération ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                <form action="{% url 'suppression_operation' item.id %}" method="post" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Supprimer</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock content_Branch_manage %}

{% block scripts %}
<script>
    document.getElementById('voir-operation-btn').addEventListener('click', function() {
        window.location.href = "{% url 'voir_operation' %}";
    });
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    $(document).ready(function() {
        $('#id_Numero_titre').change(function() {
            var numero_titre_id = $(this).val();
            $.ajax({
                url: "{% url 'afficherchampsauto' %}",
                data: {
                    'Numero_titre': numero_titre_id
                },
                dataType: 'json',
                success: function(data) {
                    $('#id_beneficiaire').val(data.beneficiaire);
                    $('#id_nni').val(data.nni);
                }
            });
        });
    });
</script>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    // Votre script qui utilise jQuery
    $(document).ready(function(){
        $('#search').on('keyup', function(){
            var value = $(this).val().toLowerCase();
            $('#myTable tr').filter(function(){
                $(this).toggle($(this).text().toLocaleLowerCase().indexOf(value) > -1);
            });
        });
    });
</script>
{% endblock scripts %}

Agence/AppChefAgence/templates/Base_branch_manage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>AgenceConnect</title>
 <!-- plugins:css -->
<link rel="stylesheet" href="{% static 'static/vendors/feather/feather.css' %}">
<link rel="stylesheet" href="{% static 'static/vendors/mdi/css/materialdesignicons.min.css' %}">
<link rel="stylesheet" href="{% static 'static/vendors/ti-icons/css/themify-icons.css' %}">
<link rel="stylesheet" href="{% static 'static/vendors/typicons/typicons.css' %}">
<link rel="stylesheet" href="{% static 'static/vendors/simple-line-icons/css/simple-line-icons.css' %}">
<link rel="stylesheet" href="{% static 'static/vendors/css/vendor.bundle.base.css' %}">

<!-- endinject -->
<!-- Plugin css for this page -->
<link rel="stylesheet" href="{% static 'static/js/select.dataTables.min.css' %}">
<!-- End plugin css for this page -->
<!-- inject:css -->
<link rel="stylesheet" href="{% static 'static/css/vertical-layout-light/style.css' %}">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Link Bootstrap Icons (Optional) -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
<!-- endinject -->
<link rel="shortcut icon" href="{% static 'static/images/favicon.png' %}" />
</head>

<body>

  {% include '_navbar_Branch_manage.html' %}

  {% include '_sidebar_Branch_manage.html' %}


  
  {% block  content_Branch_manage%}






  {% endblock content_Branch_manage %}

  

</div>


 


  {% block scripts %}
   
  {% endblock scripts %}







  <!-- plugins:js -->
<script src="/static/js/bootstrap.min.js"></script>
<script src="{% static 'static/vendors/js/vendor.bundle.base.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<script src="{% static 'static/vendors/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'static/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'static/vendors/progressbar.js/progressbar.min.js' %}"></script>
<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="{% static 'static/js/off-canvas.js' %}"></script>
<script src="{% static 'static/js/hoverable-collapse.js' %}"></script>
<script src="{% static 'static/js/template.js' %}"></script>
<script src="{% static 'static/js/settings.js' %}"></script>
<script src="{% static 'static/js/todolist.js' %}"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="{% static 'static/js/dashboard.js' %}"></script>
<script src="{% static 'static/js/Chart.roundedBarCharts.js' %}"></script>
<!-- End custom js for this page-->








</body>

</html>

Agence/AppChefAgence/templates/Created_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    
    <!-- CSS personnalisé -->

    

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery.js"></script>

    <title>PDF</title>
</head>
<body>

  <section class="site-section bg-light" id="contact-section" data-aos="fade">
    <div class="container">
      <div class="p-5 bg-white">
        <div class="row">
          <div class="col">
     
            <h2 class="col-12 text-center">Liste des Opérations</h2>
  
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col" class="col-sm-1">N° ORDRE</th>
                      <th scope="col" class="col-sm-2">N° TITRE</th>
                      <th scope="col" class="col-sm-4">BÉNÉFICIAIRE</th>
                      <th scope="col" class="col-sm-2">NNI</th>
                      <th scope="col" class="col-sm-1">MONTANT</th>
                      <th scope="col" class="col-sm-2">DATE D'OPÉRATION</th>
                    </tr>
                  </thead>
                  <tbody id="myTable">
                    {% for item in operate %}
                      <tr>
                        <td>{{ item.ordre }}</td>
                        <td>{{ item.Numero_titre }}</td>
                        <td>{{ item.beneficiaire }}</td>
                        <td>{{ item.nni }}</td>
                        <td>{{ item.montant }}</td>
                        <td>{{ item.date_operation }}</td>
                      </tr>
                    {% endfor %}
                    <tr>
                      <th scope="col">TOTAL</th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                      <th scope="col"></th>
                      <th scope="col">{{ total_montant }}</th>
                      <th scope="col"></th>
                    </tr>
                  </tbody>
                </table>
              </div>
           
          </div>
        </div>

      </div>
    </div>

  </section>

</body>
</html>

Agence/AppChefAgence/templates/Update_operation.html
{% extends 'Base_branch_manage.html' %}
{% block content_Branch_manage %}

<section class="site-section bg-light" id="contact-section" data-aos="fade">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-5">
            
               
                <form action=""class="p-5 bg-white" method="POST" >
                    <h2 class="col-12 text-center">Modifier une operation  </h2>
                   
                    {% csrf_token %}
                    {{ form.as_p }}
              
                    <input type="submit" class="btn btn-primary btn-md text-whites" value="Modifier">
                     <button class="btn btn-primary btn-md text-whites" >
                        <a href="{% url 'operateretraite' %}"> Retour</a>
                    </button>
                 
                    </form>
                               
                  
                </form>
             
              
           
        
            </div>
      
          </div>
    
    </div>
    </section>

   

{% endblock content_Branch_manage %}

Agence/AppChefAgence/templates/_footer_Branch_manage.html
<footer class="footer">
  <div class="d-sm-flex justify-content-center justify-content-sm-between">
    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Premium <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap admin template</a> from BootstrapDash.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
  </div>
</footer>